[package]
name = "srml-anyupgrade"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
support = { package = "srml-support", path = "../vendor/substrate/srml/support", default-features = false }
system = { package = "srml-system", path = "../vendor/substrate/srml/system", default-features = false }
sr-primitives = { path = "../vendor/substrate/core/sr-primitives", default-features = false }
rstd = { package = "sr-std", path = "../vendor/substrate/core/sr-std", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
inherents = { package = "substrate-inherents", path = "../vendor/substrate/core/inherents", default-features = false }

[features]
default = ["std"]
std = [
	"support/std",
	"system/std",
	"sr-primitives/std",
	"rstd/std",
	"codec/std",
	"inherents/std",
]
